name: Build and Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - charts/**

jobs:
  build-push-gia-agent:
    uses: VersesTech/github-actions/.github/workflows/build-push.yaml@main
    secrets: inherit
    with:
      service-name: gia-agent
